version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - app-network

  
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/images:/app/images
    depends_on:
      - db
    networks:
      - app-network  # Используем сеть для связи между сервисами

volumes:
  postgres_data:

networks:
  app-network:  # Создаем сеть для связи между сервисами
    driver: bridge
