version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"  # Порт для доступа к MongoDB
    volumes:
      - mongo_data:/data/db  # Хранение данных на локальной машине
  
  # backend:
  #   build: ./backend
  #   container_name: backend
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./backend/images:/app/images
  #   depends_on:
  #     - mongo
volumes:
  mongo_data:
